commit 3

diff --git a/.github/workflows/website-portofolio-saya.yml b/.github/workflows/website-portofolio-saya.yml
--- a/.github/workflows/website-portofolio-saya.yml
+++ b/.github/workflows/website-portofolio-saya.yml
@@ -23,21 +23,16 @@ jobs:
       - name: Build Project
         run: npm run build
 
-      - name: Verify Build Output
+      - name: List Files After Build
         run: |
-          if [ -d "./temp-dist" ]; then
-            echo "Directory exists."
-            ls -la ./temp-dist
-          else
-            echo "Directory does not exist."
-            exit 1
-          fi
+          ls -la
+          ls -la ./build || echo "build directory not found after build"
 
       - name: Upload artifact to enable deployment
         uses: actions/upload-artifact@v4
         with:
           name: production-files
-          path: ./temp-dist
+          path: ./build
 
   deploy:
     needs: build
@@ -50,20 +45,15 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: production-files
-          path: ./temp-dist
+          path: ./build
 
-      - name: Verify Downloaded Artifact
+      - name: List Files After Download
         run: |
-          if [ -d "./temp-dist" ]; then
-            echo "Directory exists."
-            ls -la ./temp-dist
-          else
-            echo "Directory does not exist."
-            exit 1
-          fi
+          ls -la
+          ls -la ./build || echo "build directory not found after download"
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.PORTOFOLIOKU_TOKEN }}
-          publish_dir: ./temp-dist
+          publish_dir: ./build
